# numpy Library
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

To use it, you must import the numpy module:

In [2]:
import numpy as np

to check numpy version you can use the code below:

In [2]:
print(np.__version__)

1.20.3


#### make a NumPy array
to make a NumPy array we can use np.array(), the value can be int, list, tuple, and other data typr in python.

In [14]:
# use a list to create a NumPy array
arr_list = np.array([True,2,"tiga",4,"lima"])
print(arr_list)
print(type(arr_list))

['True' '2' 'tiga' '4' 'lima']
<class 'numpy.ndarray'>


In [15]:
# use a tuple to create a NumPy array
arr_tuple = np.array((True,2,"tiga",4,"lima"))
print(arr_tuple)
print(type(arr_tuple))

['True' '2' 'tiga' '4' 'lima']
<class 'numpy.ndarray'>


#### Dimension in NumPy array
NumPy array can store multiple dimension of array, here the example:

In [21]:
# 0 Dimension
arr = np.array(11)
print(arr)

11


In [22]:
# 1 Dimension
arr = np.array([11,12,13])
print(arr)

[11 12 13]


In [25]:
# 2 Dimension
arr = np.array([[11,12],[13,14]])
print(arr)

[[11 12]
 [13 14]]


In [26]:
# 3 Dimension
arr = np.array([[[11,12,13],[14,15,16],[17,18,19]]])
print(arr)

[[[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [27]:
# 4 Dimension
arr = np.array([[[[11,12,13,14],[15,16,17,18],[19,20,21,22]]]])
print(arr)

[[[[11 12 13 14]
   [15 16 17 18]
   [19 20 21 22]]]]


the dimension is also can be set by ndmin value:

In [4]:
arr1 = np.array(11, ndmin = 5) # set 5 Dimension

to check the Dimension of the array we can use print((array name).ndim), check the code below:

In [31]:
import numpy as np
arr1 = np.array(11)
arr2 = np.array([11,12,13])
arr3 = np.array([[11,12],[13,14]])
arr4 = np.array([[[11,12,13],[14,15,16],[17,18,19]]])
arr5 = np.array([[[[11,12,13,14],[15,16,17,18],[19,20,21,22]]]])
arr6 = np.array([[[[[11,12,13,14],[15,16,17,18],[19,20,21,22]]]]])


print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)

0
1
2
3
4
5


#### get element of NumPy array 
to get an item from NumPy array we can use index just line acccing list or tuple in python.

In [7]:
# make a NumPy array
arr = np.array([1,2,3,4])

In [8]:
# access index 0
print(arr[0])

1


In [35]:
# access index 1
print(arr[1])

2


In [37]:
# access index 2 and index 3 then sum it
print(arr[2]+arr[3])

7


#### slicing in NumPy array

In [38]:
# make a NumPy array
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [39]:
# slicing with 2 parameters
print(arr[3:5])

[4 5]


the code above show item index in range 3 to 5

In [40]:
# # slicing with 3 parameters
print(arr[0:8:2])

[1 3 5 7]


the code above show item in index range 0 to 8 with 2 spaces

#### access list of multipe dimension

In [12]:
# make a 3 dimensional NumPy array
arr = np.array([[[11,12,13],[14,15,16],[17,18,19]]])
print(arr.ndim)

3


In [53]:
# access item in 1st dimension
print(arr[0])

[[11 12 13]
 [14 15 16]
 [17 18 19]]


print item index 0 in the 1st dimension

In [13]:
# access item in 2nd dimension
print(arr[0,1])

[14 15 16]


access item index 0 in the 1st dimension, than print index 1 in the 2nd dimension.

In [51]:
# access item in 3rd dimension
print(arr[0,0,1])

12


access item index 0 in the 1st dimension, access index 0 in the 2nd dimension, than print index 1 in the 3rd dimension.

#### access list of multiple dimension and slicing

In [64]:
# make a 3 dimensional NumPy array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[11,12,13],[14,15,16],[17,18,19]]])
print(arr.ndim)

3


In [65]:
# access item in 2nd dimension with slicing in 2nd dimension
print(arr[0, 0:2])

[[1 2 3]
 [4 5 6]]


access item index 0 in the 1st dimension, than print index 0 to 2 in the 2nd dimension.

In [67]:
# access item in 2nd dimension with slicing in 1st dimension
print(arr[0:2, 0])

[[ 1  2  3]
 [11 12 13]]


access item index 0 to 2 in the 1st dimension, than print index 0 in the 2nd dimension.

In [68]:
# access item in 2nd dimension with slicing in 1st and 2nd dimension
print(arr[0:2, 0:2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


access item index 0 to 2 in the 1st dimension, than print index 0 to 2 in the 2nd dimension.